apiVersion: v1
kind: Pod
metadata:
  name: ceph-test-app2
  namespace: default
spec:
  containers:
    - name: test
      image: nginx:1.27
      command:
        - /bin/sh
        - -c
        - |
          echo "Ceph RBD volume mounted successfully"
          echo "hello from Rook Ceph" > /data/test.txt
          while true; do
            date
            cat /data/test.txt
            sleep 30
          done
      volumeMounts:
        - name: ceph-volume
          mountPath: /data

  volumes:
    - name: ceph-volume
      persistentVolumeClaim:
        claimName: ceph-test-pvc