apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-test-pvc
spec:
  accessModes:
  storageClassName: rook-ceph-block # Uses the StorageClass we just created above
  resources:
    requests:
      storage: 10Gi
      
---
apiVersion: v1
kind: Pod
metadata:
  name: ceph-test-app
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    volumeMounts:
    - mountPath: /usr/share/nginx/html # Path inside the container where Ceph will mount
      name: ceph-volume
  volumes:
  - name: ceph-volume
    persistentVolumeClaim:
      claimName: ceph-test-pvc
